spring:
  profiles:
    active: local   # hoặc 'dev', thay đổi khi deploy

# Các config chung cho cả local và dev (nếu có)
jwt:
  secret: binhdeptrainhatmck12kj782361478kjsdfhk98mc3425a231
  expiration: 3600000
server:
  port: 8081
